### PR TITLE
Drop backwards compatibility with old components

### PR DESCRIPTION
**Pull request by thiemowmde**

### CODE REVIEW

**Comment by Ladsgroup** [comment]
Dropping deprecated features should require a major release. Are we planning to do so?

**Comment by thiemowmde** [comment]
Nope. This does not remove any feature **this** component provides. Raising a required version number does not mean the code in **this** component becomes incompatible, and is not a breaking change. Ask @JeroenDeDauw, he can explain this quite well.

**Comment by manicki** [comment]
Yeah, no part of public interface is removed so this does not make this change a breaking one in my understanding.
OTOH, as it also drops some compatibility with data-values/interfaces and data-values/common, I guess this could be argued as a breaking change, couldn't it?

**Comment by thiemowmde** [comment]
What do you mean with "drop compatibility"? It is still compatible. Just some more specific requirements on the version. But Composer will figure this out. This still does not make this a breaking change.

**Comment by JeroenDeDauw** [comment]
1. Assuming these changes do not affect the public API, and it looks like they do not, they do not require a major release.
2. Changes to package requirements, be it PHP version or versions of depended upon packages, do not require a major release, as long as these requirements are tracked by the package manager. So again, no major release needed

**Pull request merged**
