### PR TITLE
 Add ALL the type hints 

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Including update of dev dependencies

image

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
> Please also consider opening a "php7" branch instead of dropping PHP 5.6 compatibility from master.

I did and decided not to since that is almost certainly ending up as more work. This would be different if the component saw active development.

**Comment by thiemowmde** [comment]
> This would be different if the component saw active development.

When I look at the Phabricator tickets related to coordinates, as well as the pull requests that have been incoming the past months, I see active development happening. That would be more cumbersome if it would need to be continued in a named branch, and mirrored in an other.

Pinging @lydiapintscher, because she knows better what is planned next in the field of coordinates.

@JeroenDeDauw, why can't you use the component as it is? After all it is already compatible with all PHP 7 versions. What blocks you in doing so?

**Comment by JeroenDeDauw** [comment]
The PRs in the past months are almost all about code style. This one is as well.

Honestly I think this is not worth discussing again. We already did that for Diff when I created a PHP7 version of that component. The time and energy spend on discussion there was bigger than any other cost. And so will it be here if you again pull in a bunch of different people over something that is a non-issue.

**Comment by thiemowmde** [comment]
I ask the same questions I ask in every incoming review that does not explain it's motivation and impact. What project and team needs this update? Is this connected to https://phabricator.wikimedia.org/T178136? Would it be ok for this patch to wait, or is it blocking something?

It's your decision if you don't want to be transparent. But please don't expect me to back such a lone-wolf behavior.

**Comment by addshore** [comment]
So moving to php7 is on the horizon for the WMF https://phabricator.wikimedia.org/T176370

Releasing a 4.0.0 of Geo and then needing to add new features (or something) for Wikibase would be super annoying, as then we would have to create some other release? I mean, we could create 5.0.0 which would be PHP 5 compatible again, but that would suck.

In theory we could have a release with a prefix or a suffix? for example php5-4.0.0 or something, but all of this sucks a bit.

I'd rather just wait until these things aren't going to possibly happen.
We could merge this into a php7 branch for now?

**Comment by JeroenDeDauw** [comment]
Why would a new major release need to be created? Normally this happens for code cleanup reasons. We just had one such release that has taken the obvious breaking changes off the board. If there is a bugfix, then this can be branched off 3.0.0 and tagged as 3.0.1. If there is a new feature, the same but with 3.1.0 tag.

**Comment by RazShutyWMDE** [comment]
Hey Jeroen,

I do appreciate the code, it looks really great, sadly though it would mean that will not be able to use it as we are right now on PHP 5.

I think forking it / creating a "PHP7-Master" branch from it would be the best solution for us at WMDE and WMF:

1. Because we could still use this current solution without issues
2. It would give us something to aspire to be, the branch we want to use once we will be able to move to PHP7.

**Comment by RazShutyWMDE** [comment]
I would argue from perspective of WMDE that "marginally better for WMDE" > not "marginally better for WMDE" 

So I would love it to be a PHP7 branch or a fork of this called "GeoPHP7" and that could be the master there...

I totally understand your position, but I think for now we need to consider what is right for WMDE even though it might be not a lot of work, we just can't tell what the future has for this and this could lead to some issues

**Comment by JeroenDeDauw** [comment]
>  "marginally better for WMDE" > not "marginally better for WMDE"

You wrote the same thing twice?

You did not answer my question: are you fine with a release on a php7 branch or not?

**Comment by thiemowmde** [comment]
I'm also waiting for answers to my questions, @JeroenDeDauw.

**Comment by JeroenDeDauw** [comment]
@thiemowmde perhaps if you dropped the judgmental language and accusations I would feel inclined to talk to you

**Comment by RazShutyWMDE** [comment]
Hey ya'll, I think this is escalating a bit to a point of no value to anyone, let's talk tomorrow and resolve this face 2 face. 

@thiemowmde @JeroenDeDauw (@addshore i can call you on hangouts if you want to join)

**Comment by RazShutyWMDE** [comment]
> are you fine with a release on a php7 branch or not?
No, as I said before - I want to keep in mind that what we do in the WMDE repo is done for the purpose of helping WMDE only and I ask if we are breaking WMDEs standards then to fork this into your own repo and work from there on it OR fork it and create a php7 branch and work on it there. 

But in my opinion a release must be on the branch that supports WMDE.

**Comment by JeroenDeDauw** [comment]
Well, I did present a compromise. Sad to see this change will be completely blocked from WMDE side. Now the thing with forking this repo is... I already did that. Many years ago. This is the fork. It is not WMDE owned. WMDE switched to it. So not only did the original code get written by me outside of WMDE for the extension that benefits from this PR, the repo itself is mine. Hence WMDE can fork if it wants. Which is not a nice outcome. --NonWmdeJeroen

**Comment by RazShutyWMDE** [comment]
Are you serious? you just merged it? 

After all the discussions we had and after everything that we said? That's not OK! and also, what is a "NonWmdeJeroen"? are you not employed by WMDE?!?

**Comment by JeroenDeDauw** [comment]
This repository is owned by me as a private person, and I merged it as this private person. This after trying to come to a compromise with you on what I see as a non-issue and getting a "we do not care about your usecase, go fork the code" aka "fuck you". So "are you serious" indeed.

**Pull request merged**
