### PR TITLE
Updated @since tags in LatLongParser

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by thiemowmde** [comment]
"Update" how?

Why 3 separate tickets for all 3 renamed classes? Wouldn't it have been easier to just upload a patch if there is something wrong?

**Comment by JeroenDeDauw** [comment]
I used the web UI, so no

**Comment by thiemowmde** [comment]
Oh, sorry. I got confused and missed the fact this is not an issue but an actual pull request. +2.

**Comment by thiemowmde** [comment]
Manually rebased. +2.

**Pull request merged**
