### PR TITLE
Release 1.2.0

### PR DESCRIPTION
**Pull request by thiemowmde**
Nothing in this release is "needed" anywhere, but the diff is already so big that I believe we should not wait months. Maybe wait a few weeks. Maybe we find something else to fix.

### CODE REVIEW

**Comment by manicki** [comment]
So should this be 1.2.0 or 1.1.9?

**Comment by thiemowmde** [comment]
No change is a bug that needs any prioritized fixing, so this should not be a bugfix release.

**Comment by JeroenDeDauw** [comment]
Patch releases should not include anything that is not a bugfix: http://semver.org/

(So 1.2.0 is good)

**Comment by addshore** [comment]
Seems odd as there is basically no actual code changed... but.....

**Comment by JeroenDeDauw** [comment]
Looking at the release notes, it seems like it was done differently for the last several releases. Don't think it matters much in practice though

**Pull request merged**
